<?php
/** @var $block \Alpaca\ItGoesForward\Block\Cart\Additional\Info */
?>
<?php if ($block->getIsItGoesForwardProduct()): ?>
    <div class="flex items-center gap-2 font-semibold">
        <img src="<?= $block->getViewFileUrl('Alpaca_ItGoesForward::images/sustainability.png'); ?>"
             width="18"
             height="18"
        />
        <span class="text-primary-light">
            <?= $escaper->escapeHtml(__('Forward')) ?>
        </span>
    </div>

    <style>
        [for="cart-<?= $escaper->escapeHtmlAttr($block->getItem()->getItemId()) ?>-qty"] {
            display: none;
        }
    </style>
<?php endif; ?>
